version: '2.1'

networks:
  efk:
    driver: bridge
  nginx_proxy:
    external: true

services:
#  nginx:
#    image: nginx:1.17.4
#    container_name: nginx
#    ports:
#      - "5600:5600"
#    links:
#      - kibana
#    volumes:
#       - ./nginx/:/etc/nginx/conf.d/
#       - ./nginx/.htpasswd:/etc/nginx/.htpasswd

#  fluentd:
#    build: ./fluentd
#    volumes:
#      - ./fluentd/conf:/fluentd/etc
#    links:
#      - "elasticsearch"
#    ports:
#      - "24224:24224"
#      - "24224:24224/udp"
#    networks:
#      - efk

#https://hub.docker.com/_/elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    container_name: elasticsearch
    ports:
      - "9200:9200"
    environment:
#      - xpack.security.enabled=true
#      - xpack.monitoring.enabled=true
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx3g"
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      #- ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - efk
    restart: unless-stopped

#https://hub.docker.com/_/kibana
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.4.0
    links:
      - "elasticsearch"
    expose:
      - 5601
    #volumes:
    #  - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - efk
      - nginx_proxy
    depends_on:
      - elasticsearch
    restart: unless-stopped
